# Generated by Django 5.0.6 on 2024-07-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=255)),
                ('con_email', models.EmailField(max_length=255)),
                ('con_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cou_name', models.CharField(max_length=255)),
                ('cou_image', models.FileField(null=True, upload_to='course')),
                ('coucat_id', models.CharField(max_length=255, null=True)),
                ('cou_text', models.TextField()),
            ],
        ),
    ]
