# Generated by Django 5.0.6 on 2024-07-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coucat_id',
        ),
    ]
