# Generated by Django 5.0.6 on 2024-07-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_remove_course_coucat_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
