# Generated by Django 5.0.6 on 2024-07-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cou_descri',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='cou_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='cou_text',
            field=models.TextField(null=True),
        ),
    ]
