# Generated by Django 5.0.6 on 2024-07-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_remove_order_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_user', models.CharField(max_length=250, null=True)),
                ('wish_proid', models.IntegerField(null=True)),
                ('wish_name', models.CharField(max_length=250)),
                ('wish_price', models.FloatField(max_length=250)),
                ('wish_image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
