# Generated by Django 5.0.6 on 2024-08-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_dashregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(null=True),
        ),
    ]
